# Change these first
owner: kirilloooo # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: KiroDomains
    url: https://kiro.pw
  - name: KiroMail
    url: https://m.kiro.pw
  - name: ytics
    url: https://fy.oo.gd
  - name: KiroDomains Support
    url: https://support.kiro.pw
  - name: KiroAPI
    url: https://api.kiro.pw

status-website:
  favicon: https://kiro.pw/favicon.png
  theme: night
  customHeadHtml: "<script data-host='https://fy.oo.gd' data-dnt='false' src='https://fy.oo.gd/js/script.js' id='ZwSg9rf6GA' async defer></script>"
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.zkyrylo.eu.org
  # baseUrl: /your-repo-name
  logoUrl: https://kiro.pw/favicon.ico
  name: Kiro Status Page
  introTitle: "**Kiro** free2use project. Previously called Platform Group. All projects are owned by an individual with the pseudonym Chiminori."
  introMessage: You can contact me via [e-mail](mailto:admin@kiro.pw) or [**KiroSupport**](https://support.kiro.pw).
  navbar:
    - title: Status
      href: /
